---
title: "PCA and kmeans Clustering"
author: "Dylan Fu"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse) # For data manipulation and visualization
data("iris") # Load the iris dataset
set.seed(0)
```

Step 2: Determine the first two principal components of the dataset

```{r}
# Calculate the principal components using prcomp() function
pca <- prcomp(iris[, -5], scale = TRUE)

# Extract the scores for the first two principal components
pc1 <- pca$x[, 1]
pc2 <- pca$x[, 2]
summary(pca)
```

Step 3: Create a data frame with the original and transformed variables

```{r}
# Combine the original and transformed variables into one data frame
iris_pca <- data.frame(cbind(pc1, pc2))
colnames(iris_pca)[1:2] <- c("PC1", "PC2")
```

Step 4: Plot the data on the PC axes using ggplot2

```{r}
library(ggplot2) # For plotting

# Create a scatter plot of the first two principal components
ggplot(iris_pca, aes(x = PC1, y = PC2)) +
  geom_point()
```

```{r}
inertia<-c()
for (i in 1:10){
  m<-kmeans(iris_pca, centers = i)
  inertia<-c(inertia,m$tot.withinss)
}
ggplot(data = NULL, aes(x = 1:10, y = inertia))+geom_line()+geom_point()+labs(title = "Elbow Plot", x = "n Clusters", y = "Within Cluster SS")+scale_x_continuous(breaks = pretty(1:10, n = 10))
```

```{r}
model<-kmeans(iris_pca, centers = 3)
preds<-cbind(iris_pca, model$cluster)
colnames(preds)[3]<-"Group"
ggplot(preds, aes(x = PC1, y = PC2, color = as.factor(Group))) +
  geom_point()+labs(title="Predicted Clusters")

```
